# Generated by Django 5.0.3 on 2024-03-29 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, choices=[('USA', 'Estado Unidos'), ('BRA', 'Brasil'), ('ESP', 'Espanha'), ('ENG', 'Inglaterra'), ('JPN', 'Japão'), ('POR', 'Portugal'), ('ISR', 'Israel'), ('AUS', 'Australia')], max_length=100, null=True)),
            ],
        ),
    ]
